"""add goals table

Revision ID: 8a18ed3c6e79
Revises: 04a71a0770de
Create Date: 2026-06-17 15:56:41.342292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a18ed3c6e79'
down_revision = '04a71a0770de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('estimated_total_effort_minutes', sa.Integer(), nullable=False),
    sa.Column('soft_target_date', sa.DateTime(), nullable=False),
    sa.Column('time_logged_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
